---
title: "Long Response 3: Forms of Resistance"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Format

Length: 3-5 pages, 12 point font, double spaced. 


## Overview

When ethical concerns arise as a result of algorithmic decision-making systems, how can we respond? In this long response assignment, you will select and study one remedy or form of resistance to algorithmic decision-making. Some examples to consider:

  * Regulation via legislation
  * Consumer boycotts
  * Worker-led organizing (ex. walkouts)
  * Algorithmic fairness research

In your long response, you should outline your chosen form of resistance, identify actual examples where it has been applied, and discuss when and where it could be an effective response to abuses of algorithmic decision-making.

## Instructions

1. Your long response should include the following sections:

    * **Introduction (3 points):** Introduce and define your form of resistance. Who are the main actors or participants? 
    * **Historical examples (3 points):** Identify at least two examples where your form of resistance has been used to respond to algorithmic decision-making and discuss whether it was effective.
    * **Possibilities (3 points):** What kind of ethical concerns can be addressed via your selected form of resistance? Identify ways in which your selected form of resistance could be effective.
    * **Shortcomings (3 points):** What kind of ethical concerns cannot be addressed via your selected form of resistance? Identify ways in which your selected form of resistance may not address all possible concerns?

2. Finally, your long response will also be graded on the following criterion: 

    * **Presentation/exposition (3 points):** Submissions should be carefully edited, with citations for all resources used.